### ISSUE TITLE
How to postMessage to WebView2 controller when mitigating code from WebBrowser to WebView2?

### ISSUE THREAD

**Issue by stevenchen1976** [gillesgg/WebView2_Sample#1]
Hi,
This sample is written in WTL is very useful to me, Thanks.
I am doing some work on mitigating WebBrowser to WebView2 in WTL.  I am in trouble to postMessage to WebView2 controller used in WTL dialog base application.

When use WebBrowser,  there are some code snippets
MainDlg.h
------------------------------------------------------------------------------------
private:
CAxWindow m_browserWnd;
CComPtr<IWebBrowser2> m_pWebBrowser; 

void ClickBrowser(int x, int y);
void SendBrowserChars(LPCTSTR text);
----------------------------------------------------------------------------------------

MainDlg.cpp
-----------------------------------------------------------------------------------------
m_browserWnd = GetDlgItem(IDC_BROWSER);

void CMainDlg::ClickBrowser(int x, int y)
{
  if (m_browserWnd)
  {
	m_browserWnd.PostMessage(WM_LBUTTONDOWN, MK_LBUTTON, x | (y << 16));
    m_browserWnd.PostMessage(WM_LBUTTONUP, 0, x | (y << 16));
  }
}

void CMainDlg::SendBrowserChars(LPCTSTR text)
{
  if (m_browserWnd)
  {
    for (LPCTSTR c = text; *c; c++)
      m_browserWnd.PostMessage(WM_CHAR, *c, 0);
  }
}

How can it post a message to WebView2 controller ?
It seams WebView2 controller hasn't Window like WebBrowser. Would you like to take look?
Thanks in advance.

**Comment by gillesgg** [comment]
Hi,
Post a message to the WebView2 controler like WebBrowser, will probably not working.
You can probably use PostWebMessageAsJson or by injecting JavaScript, see https://github.com/MicrosoftEdge/WebView2Samples/tree/master/SampleApps/WebView2APISample
or UIAutomation.
